services:

  # duckdns:
  #   image: lscr.io/linuxserver/duckdns:latest
  #   container_name: duckdns
  #   environment:
  #     - PUID=1000 #optional
  #     - PGID=1000 #optional
  #     - TZ=Etc/UTC #optional
  #     - SUBDOMAINS={dominio}
  #     - TOKEN={tokendominio}
  #     - LOG_FILE=false #optional
  #   #volumes:
  #   #  - /data/config:/config #optional
  #   restart: unless-stopped
  #   networks:
  #     - projetoiot
    
  node-red:
    container_name: node_red
    image: nodered/node-red:latest
    restart: always
    user: root
    privileged:  true
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    networks:
      - projetoiot
      - proxy_nginx
    volumes:
      - ./projetoiot/node-red/data:/data
      #- ./settings.js:/data/settings.js

  pgsql_mqtt:
    container_name: pgsql_mqtt
    image: timescale/timescaledb:2.9.3-pg15
    restart: always
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=${usuariobanco}
      - POSTGRES_PASSWORD=${senhabanco}
      - LANG=en_US.utf8
      - LANGUAGE=en_US.utf8
      - LC_ALL=en_US.utf8
      - LC_COLLATE=en_US.utf8
      - LC_CTYPE=en_US.utf8
      - TZ=GMT-3
    networks:
      - projetoiot
    volumes:
      - ./projetoiot/postgres:/var/lib/postgresql/data
  
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./projetoiot/mosquitto/config/:/mosquitto/config
      - ./projetoiot/mosquitto/data/:/mosquitto/data
      - ./projetoiot/mosquitto/log:/mosquitto/log
    environment:
      - MQTT_USERNAME=${usuariobanco}
      - MQTT_PASSWORD=${senhabanco}
    networks:
      - projetoiot

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

networks:
  projetoiot:
    driver: bridge
  proxy_nginx:
    external: true