services:

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Etc/UTC #optional
      - SUBDOMAINS={dominio}
      - TOKEN={tokendominio}
      - LOG_FILE=false #optional
    #volumes:
    #  - /data/config:/config #optional
    restart: unless-stopped
    networks:
      - projetoiot
    


  node-red:
    image: nodered/node-red:latest
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    networks:
      - projetoiot
    volumes:
      - /data/projetoiot/node-red/data:/data

  mysql:
    container_name: mysql
    image: mysql:8.0
    command:
      - mysqld
      - --default-authentication-plugin=mysql_native_password
    networks:
      - projetoiot
    ports:
      - '3306:3306'
    volumes:
      - '/data/projetoiot/mysql:/var/lib/data' 
    environment:
      - MYSQL_ROOT_PASSWORD=.
      - MYSQL_DATABASE={banco}
      - MYSQL_USER={usuariobanco}
      - MYSQL_PASSWORD={senhabanco}


networks:
  projetoiot:
    driver: 
        brigde