version: "3.1"
services:
  node-red:
    container_name: node_red
    image: nodered/node-red:latest
    restart: always
    user: root
    privileged:  true
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "1880:1880"
    networks:
      - projetoiot
      - proxy_nginx
    volumes:
      - ./projetoiot/node-red/data:/data
      #- ./settings.js:/data/settings.js

  pgsql_mqtt:
    container_name: pgsql_mqtt
    image: postgres:alpine3.18
    restart: always
    ports:
      - 5444:5432
    environment:
      - POSTGRES_USER=${usuariobanco}
      - POSTGRES_PASSWORD=${senhabanco}
      - LANG=en_US.utf8
      - LANGUAGE=en_US.utf8
      - LC_ALL=en_US.utf8
      - LC_COLLATE=en_US.utf8
      - LC_CTYPE=en_US.utf8
      - TZ=America/Sao_Paulo
    networks:
      - projetoiot
    volumes:
      - ./projetoiot/postgres:/var/lib/postgresql/data
  
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./projetoiot/mosquitto/config/:/mosquitto/config
      - ./projetoiot/mosquitto/data/:/mosquitto/data
      - ./projetoiot/mosquitto/log:/mosquitto/log
    environment:
      - MQTT_USERNAME=${usuariobanco}
      - MQTT_PASSWORD=${senhabanco}
    networks:
      - projetoiot

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@iot.com
  #     PGADMIN_DEFAULT_PASSWORD: Root@1234567890
  #   volumes:
  #     - .pgadmin:/root/.pgadmin
  #   ports:
  #     - "5050:80"

networks:
  projetoiot:
    driver: bridge
  proxy_nginx:
    external: true